# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: ZedIndustries.Zed
PackageVersion: 0.208.5
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2025-10-16
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://zed.dev/api/releases/stable/0.208.5/Zed-x86_64.exe
  InstallerSha256: f56cb6e2d5b5487934d32f3720aa791dcc16dc22e141f1d23e06823db43d13dc
ManifestType: installer
ManifestVersion: 1.10.0
